# Generated by Django 3.0 on 2022-08-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_protocol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tape_of_delivery',
            field=models.CharField(choices=[('P', 'P'), ('C', 'C')], default='C', max_length=1),
        ),
    ]
