# Generated by Django 3.2 on 2023-05-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_protocol', '0002_alter_order_id_alter_orderproduct_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tape_of_delivery',
            field=models.CharField(choices=[('C', 'C'), ('P', 'P')], default='C', max_length=1),
        ),
    ]
