# Generated by Django 3.0 on 2022-11-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_protocol', '0002_auto_20220829_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tape_of_delivery',
            field=models.CharField(choices=[('C', 'C'), ('P', 'P')], default='C', max_length=1),
        ),
    ]
